// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB40ua5wVfwu-8f0Teb0r3vFActyjUZd7M',
    appId: '1:1058524256754:web:35c97e9b3a36eca7c3b36b',
    messagingSenderId: '1058524256754',
    projectId: 'fintech-ace-b0215',
    authDomain: 'fintech-ace-b0215.firebaseapp.com',
    storageBucket: 'fintech-ace-b0215.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJsjuQMkFYkH3dmJPWokZn4DNda-9ly8',
    appId: '1:1058524256754:android:2cd36229d892bd8ec3b36b',
    messagingSenderId: '1058524256754',
    projectId: 'fintech-ace-b0215',
    storageBucket: 'fintech-ace-b0215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEH0qs5v54vCI30m01P8tdkmvNdI9XxVs',
    appId: '1:1058524256754:ios:047445da8f7a17a1c3b36b',
    messagingSenderId: '1058524256754',
    projectId: 'fintech-ace-b0215',
    storageBucket: 'fintech-ace-b0215.firebasestorage.app',
    iosBundleId: 'com.example.fintechAce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEH0qs5v54vCI30m01P8tdkmvNdI9XxVs',
    appId: '1:1058524256754:ios:047445da8f7a17a1c3b36b',
    messagingSenderId: '1058524256754',
    projectId: 'fintech-ace-b0215',
    storageBucket: 'fintech-ace-b0215.firebasestorage.app',
    iosBundleId: 'com.example.fintechAce',
  );
}
